# Generated by Django 3.2 on 2021-12-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to='images/logos/')),
                ('footer_logo', models.ImageField(upload_to='images/logos/')),
                ('slider_image', models.ImageField(upload_to='images/slider/')),
                ('slider_title', models.CharField(max_length=250)),
                ('slider_body', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
