# Generated by Django 3.2 on 2021-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('plan_included', models.TextField()),
                ('payment_url', models.URLField()),
                ('box_color', models.CharField(choices=[('Green', 'success'), ('Red', 'danger'), ('Yellow', 'warning')], max_length=10)),
            ],
        ),
    ]
