# Generated by Django 3.2 on 2021-12-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0003_auto_20211209_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='courses_number',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='free_video_number',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hours_number',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='student_number',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='box_color',
            field=models.CharField(choices=[('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow')], max_length=10),
        ),
    ]
