# Generated by Django 3.2 on 2021-12-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0004_auto_20211209_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/freevideo/')),
                ('iframe', models.TextField()),
                ('video_link', models.URLField()),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
