# Generated by Django 3.2 on 2021-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0007_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=250)),
                ('founder_image', models.ImageField(upload_to='images/founder/')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'About Founder',
            },
        ),
        migrations.CreateModel(
            name='FoundrFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
