# Generated by Django 3.2 on 2021-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0009_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_about',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube_channel',
            field=models.URLField(blank=True, null=True),
        ),
    ]
