# Generated by Django 3.2 on 2021-12-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0010_auto_20211218_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEnglisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englisher_name', models.CharField(max_length=250)),
                ('englisher_image', models.ImageField(upload_to='images/englisher/')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'About Englisher',
            },
        ),
        migrations.CreateModel(
            name='EnglisherFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='header_logo',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='slider_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
