# Generated by Django 3.2 on 2021-12-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0010_auto_20211218_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='header_logo',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='slider_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
