# Generated by Django 3.2 on 2021-12-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0012_aboutenglisher_englisherfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook_page',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_about',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_logo',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube_channel',
        ),
    ]
