# Generated by Django 3.2 on 2021-12-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0012_auto_20211224_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter_link',
        ),
    ]
