# Generated by Django 3.2 on 2021-12-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0013_auto_20211224_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter_link',
        ),
    ]
