# Generated by Django 3.2 on 2021-12-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0015_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
