# Generated by Django 3.2 on 2021-12-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englisher', '0017_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='email_to',
        ),
    ]
